"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
import distutils
import sys
import opcode
import os

sys.setrecursionlimit(10000)

distutils_path = os.path.join(os.path.dirname(opcode.__file__), 'distutils')

APP = ['run.py']
DATA_FILES = ['resources']
OPTIONS = {'argv_emulation': True,
 'iconfile': '/Users/sutee/Works/E-Tipitaka.icns',
 'packages': ['whoosh', 'pony', 'xhtml2pdf', 'reportlab'],
 'plist': {'CFBundleIdentifier': 'com.watnapp.etipitaka',
           'CFBundleGetInfoString': 'E-Tipitaka.app built using py2app'}
}

setup(
    name="E-Tipitaka",
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)

